### ISSUE TITLE
DOCKER_REGISTRY as ArtifactPublished location type

### ISSUE THREAD

**Issue by d-stahl-ericsson** [eiffel-community/eiffel#142]
The event current enumerates ARTIFACTORY, NEXUS, OTHER, PLAIN as legal types. I propose adding DOCKER_REGISTRY to that list.

**Comment by erobged** [comment]
we are looking to have support in Nexus for Docker so I think this would be good.

**Comment by xvinosi-github** [comment]
Will this issue also need changes in the EiffelArtifactCreatedEvent since the information in the event for the artifact we have today is mostly suitable for maven?

**Comment by d-stahl-ericsson** [comment]
You're thinking of identification via data.gav? Perhaps, but not necessarily; artifact identity and published location are two separate things. But please feel free to suggest how you think it should work.

**Comment by e-backmark-ericsson** [comment]
Hmm. Comparing DOCKER_REGISTRY with ARTIFACTORY and NEXUS is a bit like comparing pears and apples, I think. Both Artifactory and Nexus can store and serve artifacts in multiple formats using multiple services/plugins.

When it comes to Docker format, both Artifactory and Nexus can handle it. So If I have a Docker image that I would like to upload to Artifactory using Docker push, should I set DOCKER_REGISTRY or ARTIFACTORY as location type?

When it comes to determining how to authenticate towards a specific location, the _location host type_ (Artifactory or Nexus or something else) would be interesting, but when it comes to determining what method to use to upload/fetch artifacts, the _location format_ (Docker, Maven, PyPI, etc) would be interesting.

**Comment by d-stahl-ericsson** [comment]
Yes, I think you have a good point, Emil. I feel as though I don't have 100% conceptual clarity on this, so it's great that you bring it up and challenge it. Perhaps a split int location host type and location format is the way to go. Or perhaps location host type isn't really relevant. Would love some more clever people to chime in on this - until then we shouldn't merge the PR.

**Comment by d-stahl-ericsson** [comment]
Will leave the issue open because it's relevant, but closed the PR.

**Comment by d-stahl-ericsson** [comment]
I think #182 makes this obsolete.

**Comment by d-stahl-ericsson** [comment]
It is about ArtC, but it adds information about the type of artifact which is currently missing. With that information, the need to add e.g. DOCKER_REGISTRY (and potentially every other kind of repository/registry/location) is greatly reduced. In fact, I'm wondering whether location type in ArtP could be removed altogether. A purl in ArtC combined with a URI in ArtP should be all you need?

**Comment by e-backmark-ericsson** [comment]
Agreed. I don't think there is a need for a Docker specific location type. The data.identity in ArtC will tell you that the artifact you're about to fetch is packaged in Docker image format and the locations[].uri in ArtP will give you the information needed to fetch that Docker image from wherever it is published. So, given that #182 will be accepted this issue should not be valid anymore.

**Comment by d-stahl-ericsson** [comment]
This is made obsolete by #182. Closing.
