### ISSUE TITLE
Description of meta.time format should be distinct and clear

### ISSUE THREAD

**Issue by l-ohlen-ericsson** [eiffel-community/eiffel#177]
### Description
The meta.time format should be described more distinct and clear, since the current description could be miss interpreted.     

File the-meta-object.md 

### Motivation
Currently the meta.time field is described as **Milliseconds since epoch.** 
Since the Eiffel events can be generated in many different time zones,  the epoch in this context is probably referring to epoch as being UNIX Epoch time (or Unix time / POSIX time) where the time zone is then UTC. 
 
So the epoch description should either be changed to UNIX Epoch time, or to explicit have UTC time zone set. 

### Exemplification 
epoch could been interpreted as epoch in current time zone with the current description, that will lead to that events will have unaligned times. 

### Benefits 
Clear and distinct definition of epoch will ensure that event times are correctly set regardless in which time zone they are created 

### Possible Drawbacks
None

**Comment by d-stahl-ericsson** [comment]
Sure, let's just call it UNIX Epoch time.
