### ISSUE TITLE
Security on EiffelActivityTriggeredEvent and EiffelActivityStartedEvent needs to be updated

### ISSUE THREAD

**Issue by SantoshNC68** [eiffel-community/eiffel#205]
### Description
The EiffelActivityTriggeredEvent and EiffelActivityStartedEvent contains security that is not updated to Agen Edition.(contains same info as tolouse events).
Need to update the schemas for both the events with latest security.

**Comment by e-backmark-ericsson** [comment]
Changing these two event types is non backwards compatible. Therefore we need to step the major version of those event schemas. Also, according to [the versioning documentation](https://github.com/eiffel-community/eiffel/blob/master/eiffel-syntax-and-usage/versioning.md#updating-historical-event-types-and-editions) a new release with these updated events should be called 'edition-agen-1' if I read that documentation correctly.

**Comment by SantoshNC68** [comment]
Ok, so we need to release it with edition-agen-1 tag with the fix to these events.
Would the events have major version like 4.0.0 to these events in that case ?

**Comment by e-backmark-ericsson** [comment]
Yes, that's my understanding. I'll create a PR.

**Comment by e-backmark-ericsson** [comment]
Solved with PR #206
