### ISSUE TITLE
Documenation bug in EiffelArtifactCreatedEvent, still refers to data.gav.

### ISSUE THREAD

**Issue by martin-at-ericsson** [eiffel-community/eiffel#209]
### Description
The EiffelArtifactCreatedEvent documentation still refers to data.gav (instead of data.identity) in the description of data.name.

### Motivation
Bug (left-over) since GAV to PURL update.

### Exemplification
see Description

### Benefits
Correct documentation.

### Possible Drawbacks
None.

**Comment by e-backmark-ericsson** [comment]
Closing this as the merged PR solves the issue.
