### ISSUE TITLE
Move Code of Conduct to eiffel-community/community repository

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/eiffel#210]
### Description
Eiffel Community is home for multiple projects, including but not limited to protocol itself, easy2use, remrem and so on. All repositories contain code of conduct document which is unnecessary duplication, could cause confusion due to having document for the same purpose within all the repositories, and also introduces risk of divergence across different repositories. It is valuable and important to keep the community-wide guidelines such as code of conduct in one place and refer to it from all the repositories that are currently under eiffel-community. The repository template, eiffel-repository-template, should also be adapted to include the reference to the one in eiffel-community/community repository.
 
### Motivation
The same code of conduct shall be applicable to all the contributors no matter what Eiffel project/repository they will be contributing to. It is important for the existing and new contributors to look at single/same reference for code of conduct guideline that is kept up to date centrally.

### Exemplification
Majority of the open source communities have single code of conduct that is maintained in one place and applied to all the projects that take part in the community.

- CNCF: https://github.com/cncf/foundation/blob/master/code-of-conduct.md
- OPNFV: https://wiki.opnfv.org/display/DEV/OPNFV+Community+Code+of+Conduct
- OpenStack: https://www.openstack.org/legal/community-code-of-conduct/

### Benefits
The code of conduct will be maintained in one place/centrally, easing the community to refer to it no matter what part of Eiffel they are contributing to and reduce the possibility of divergence.

### Possible Drawbacks
None

**Comment by e-pettersson-ericsson** [comment]
Just a hint to also update the github.io page when this file is moved out from the repository. https://eiffel-community.github.io/ links to the current Code of conduct file located here, and to avoid broken links we should update github.io also.

**Comment by e-backmark-ericsson** [comment]
@e-pettersson-ericsson , the github.io pages doesn't link to this Code of conduct document anymore, does it?

**Comment by e-pettersson-ericsson** [comment]
@e-backmark-ericsson no it doesn't, not anymore :)
