### ISSUE TITLE
Broken links in introduction document

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel#215]
### Description
Some links are broken in the introduction document.
https://github.com/eiffel-community/eiffel/blob/master/introduction/introduction.md

### Motivation
Documentation should not have broken links.

### Exemplification
Broken links mean documentation is not complete

### Benefits
Correct documentation.

### Possible Drawbacks
Linking to an external page (sepia) could be "dangerous" as there is no control of it in this repository. But it's better than broken links, which we have now.

**Comment by e-backmark-ericsson** [comment]
Just as a reference here, the broken links refer to content removed in this PR: #193
