### ISSUE TITLE
Couldn't CompositionDefined link to SourceChangeCreated?

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel#218]
### Description
EiffelCompositionDefinedEvent can have an ELEMENT link pointing at an EiffelSourceChangeSubmittedEvent. This is a natural fit for post-merge/production pipelines, but what about pre-merge/review pipelines? I lack the possibility to link EiffelCompositionDefinedEvent to EiffelSourceChangeCreatedEvent using an ELEMENT link. Is there a reason not to allow that?

### Motivation
This reference is missing

### Exemplification
As in description

### Benefits
Makes it possible to trace build and tests in a pre-merge/review pipeline better.

### Possible Drawbacks
None

**Comment by magnusbaeck** [comment]
Agreed, although a workaround could be to emit SCS events for the refs/changes/X/Y/Z refs created each time a patch set is created in Gerrit. For PR/MR based review systems like Github and Gitlab where the author can rewrite the branch this probably won't work.

**Comment by e-backmark-ericsson** [comment]
The SCS signals that a change has been merged, so I don't see it as an option for a 'pre-merge' activity. The intention is that the SCC and SCS events should valid regardless of SCM system, being it Gerrit, Gitlab, Github or any other. Do you doubt that?
