### ISSUE TITLE
how to deploy eiffel do some test?

### ISSUE THREAD

**Issue by iver3on** [eiffel-community/eiffel#222]
I am a beginner of Eiffel, I want to deploy a system, do a macro understanding, and test it.

**Comment by e-pettersson-ericsson** [comment]
I'm not sure I understand what you are referring to in this issue. If you could fill out the template it would really help us in understanding what you want to achieve 😄 

In the meantime, have you tried to take a look at https://github.com/eiffel-community/eiffel-easy2use to try out several Eiffel components together with the protocol?

**Comment by iver3on** [comment]
@e-pettersson-ericsson  haha,I am a beginner of Eiffel, I want to deploy an  eiffel system, do a macro understanding, and test it.

**Comment by e-backmark-ericsson** [comment]
@iver3on , as @e-pettersson-ericsson said, I would suggest you take a look at the Easy2Use sandbox. That would give you the possibility to deploy a set of Eiffel eco-system components by yourself and test it.
You could also look at the https://eiffel-community.github.io/eiffel-sepia/, which is a suggested implementation architecture. It should hopefully give you the macro understanding you're asking for.
I consider this issue solved.

**Comment by e-pettersson-ericsson** [comment]
@iver3on Well, [easy2use](https://github.com/eiffel-community/eiffel-easy2use) contains, among other things, a "bundle" of Eiffel related services and a CLI to quickly start up the environment and get going. If you are familiar with Docker and want to try specific services the [easy2use Eiffel bundle](https://github.com/eiffel-community/eiffel-easy2use/tree/master/bundles/Eiffel) comes with pre-configured services (such as Eiffel message bus and REMReM etc) to try out. The REMReM service on GitHub comes pre-installed with the Eiffel message protocol. You can read about [how to get started with easy2use](https://github.com/eiffel-community/eiffel-easy2use/blob/master/wiki/markdown/Getting_Started.md).
