### ISSUE TITLE
ArtC example contains multiple id

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel#228]
### Description
The id field is duplicated in the simpel example of ArtifactCreated event.
https://github.com/eiffel-community/eiffel/blob/master/examples/events/EiffelArtifactCreatedEvent/simple.json

### Motivation
The example events should be correct.

### Benefits
See motivation above.

### Possible Drawbacks
None.

**Comment by e-backmark-ericsson** [comment]
I agree. This should be corrected.
