### ISSUE TITLE
New link type from ActT to ArtC

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel#230]
### Description
TestCaseTriggered events have a relationship to ArtifactCreated events with the IUT link type. I am missing a similar relationship between ActivityTriggered to ArtifactCreated. In the particular use case I'm thinking of we are not testing the built artifact so we can not use those events. Rather, we are performing PLM operations on a built artifact, and we would like a way to refer to a specific artifact from an activity.

Another example I can think of, could be if we want to have a release flow started for this newly created artifact. If we have release activities concerning an artifact, it could be useful with such a link (instead of CAUSE). These release activities could be other than just publishing (ArtP for that) - it could for instance be creation of release notes.

I couldn't find any explicit mention of naming conventions of the link types - are verbs allowed, or should they be nouns only? Perhaps I'll create a separate issue for clarifying this.

### Motivation
The existing link type CAUSE is not really fit for our use case, since the activity in itself is not really caused by the build of an artifact. We are looking for a link type which means that this activity CONCERNS a particular artifact.

### Exemplification
I'm still trying to figure out a good name of this new link type, perhaps SUBJECT could be re-used? CLM refers to ArtC with this link type, stating that this artifact has received this confidence level. Or TOPIC? Or CONCERNS?

### Benefits
It will be possible to tie activities explicitly to artifacts (as explained above, sometimes the CAUSE link is not always appropriate).

### Possible Drawbacks
I can't think of any right now. Perhaps someone else has concerns regarding this.

**Comment by e-backmark-ericsson** [comment]
This is somewhat related to #227 as well. CAUSE is not really fit for purpose for all kinds of trigger types in an ActT event either. I believe it is quite common to link an activity representing a pipeline execution to a SCC/SCS event using a CAUSE link, and that is fine when it is triggered automatically, but not really when the pipeline is (re)triggered manually, where ActT.data.triggers[].type is probably set to 'MANUAL'.

**Comment by magnusbaeck** [comment]
We discussed this at the 2021-05-27 Eiffel event workshop and reached the conclusion that an activity can be triggered by another event (a CAUSE link) but expressing a general "this activity is somehow related to this other event" isn't a good fit for a "container entity" like an activity. It doesn't express the nature of the relationship and therefore carries very little meaning.

> In the particular use case I'm thinking of we are not testing the built artifact so we can not use those events. Rather, we are performing PLM operations on a built artifact, and we would like a way to refer to a specific artifact from an activity.

If you want to express PLM operations and point to the concerned artifact, aren't you actually missing a way to express the PLM operation itself? Perhaps something like EiffelArtifactPromotedEvent would be better?

> Another example I can think of, could be if we want to have a release flow started for this newly created artifact. If we have release activities concerning an artifact, it could be useful with such a link (instead of CAUSE). These release activities could be other than just publishing (ArtP for that) - it could for instance be creation of release notes.

But wouldn't those release notes be modeled with an ArtC that could have a CAUSE link to the released artifact?

I'm inclined to close this issue as a "won't do" but please speak up @e-pettersson-ericsson if there's some aspect I'm overlooking.

**Comment by magnusbaeck** [comment]
No response from issue creator for a couple of months so I'm closing this.
