### ISSUE TITLE
Provide Guidelines on version handling of endpoints across the eiffel-community

### ISSUE THREAD

**Issue by SantoshNC68** [eiffel-community/eiffel#232]
### Description
There is no common guidelines about how to support the version handling and how long we should support the deprecated endpoints. This issue is create to make a guidelines available across the community so that we adhere the same across different repositories

### Motivation
We have different repositories adhering to different ways w.r.t version handling of endpoints, so this can be brought in as a common way to support them.

**Comment by e-backmark-ericsson** [comment]
I agree it would be good to have a common guideline on how REST APIs in general and version handling in REST APIs in specifically should work across tools in the Eiffel eco-system.
I guess we should get input from looking at for example Swagger, RAML, Open API. We could also look at this recommendation from Zalando before we decide on our best practices here: https://opensource.zalando.com/restful-api-guidelines/
We should collect the current used standards in our existing Eiffel eco-system tools and relate them to current best practices in the open source world and set our own baseline for such guidelines (or just point to an existing one).

**Comment by e-backmark-ericsson** [comment]
This issue does actually not belong in the Eiffel protocol repo, as it is about eco-system tools and not about the protocol. Should it be added to the Community repo maybe https://github.com/eiffel-community/community? Or do you think we'd need a new repo to keep common Eiffel Eco System documents/sources?

**Comment by SantoshNC68** [comment]
I agree, I will write it in the community instead and will close this.

**Comment by SantoshNC68** [comment]
Created an issue in community https://github.com/eiffel-community/community/issues/35 and closing this one.
