### ISSUE TITLE
Add batch level configuration to TERCC

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel#241]
### Description

The EiffelTestExecutionRecipeCollectionCreated (TERCC) event currently as a "constraints" field that can be used for recipe-level configuration. This is really great. However there is no way to configure the TERCC on a batch level. A configuration that applies to the environment in which to run or on every recipe in the TERCC.

### Motivation

Today we are using the "data.customData" field for this type of information and would like to move away from that.

### Exemplification

The "data.customData" field is used today for selecting from where to get the IUT from. The configuration field would be able to give us this information instead.
This field could also be used to override the environment provider, we're using in our test orchestration system, on a suite level.

### Benefits

Avoiding the usage of the customData field is always a benefit.

### Possible Drawbacks

Not sure if this field will be usable by others. Might add unnecessary clutter.

**Comment by k-hallen-ericsson** [comment]
I've asked some Ericsson people that use TERCCs more than me to review. /Kristofer

**Comment by e-backmark-ericsson** [comment]
I'm glad to see your involvement here, @t-persson! I'll comment on this request soon, but it might not be until early next week. This day is so busy.

**Comment by a-broman-ericsson** [comment]
This would be a convenience addition to the TERCC event. One thing to keep in mind is that if test configuration constraints are added on Batch level, they may still exist on recipe level and there is a risk for conflict between the constraints stated on the recipe and the constraints stated on the Batch level. Also, even if there are no conflicts, the user of the TERCC information need to combine the batch and recipe constraints to get the full set of constraints for each recipe. So, if we would introduce Batch level constraints, ti should be clearly stated that these dependecies are there.

**Comment by k-hallen-ericsson** [comment]
Positive feedback, @e-backmark-ericsson do you have anything to add? Since protocol changes have a big impact I would like to see as much input as possible before going for decision.

**Comment by a-broman-ericsson** [comment]
A potential problem could be that the testcasetriggered event has a reference to the recipeid and a listener to this message can get the impression that the recipe is complete, which it may not be if we allow recipe information also on batch level.

Here is the part from the testcasetriggeredevent I am referring to.

data.recipeId
Type: String
Required: No
Description: If triggering this test case execution was the result of an Execution Recipe, as defined by an EiffelTestExecutionRecipeCollectionCreatedEvent, this UUID SHALL match the relevant data.batches.recipes.id in that event.

**Comment by e-backmark-ericsson** [comment]
That's a good insightful comment, @a-broman-ericsson. @t-persson, have you considered that? Do you use the data.recipeId parameter in TCT? We should probably at least document this as a note on the TCT definition page, so that consumers of TCT are aware of it.

**Comment by k-hallen-ericsson** [comment]
@a-broman-ericsson @t-persson any thoughts on Emils question above?

**Comment by t-persson** [comment]
@k-hallen-ericsson missed this one. sorry!

@a-broman-ericsson Good find!

@e-backmark-ericsson  @a-broman-ericsson These are valid questions. We don't currently use the data.recipeId at the moment, but might do in the future.
That parameter does pose a problem for this new parameter though, because we don't want users of the TCT data.recipeId to have to find information about the recipe in different places. It would make it more difficult to use the parameter and I don't like it.

We wanted a way to override and to configure every recipe on a higher level in order to prepare an environment before starting execution.
Since, with this new information, I believe that my suggestion would cause more problems than it would solve; does anyone have any alternatives to the suggested solution from me?

**Comment by e-backmark-ericsson** [comment]
@t-persson , would it be possible in your case to somehow aggregate/merge the constraints from the recipes and set up the test environment based on that?

**Comment by t-persson** [comment]
We do something similar to that, but we want to also be able to override.

Our suggested solution, after comments in this thread, is this:

1. Send a TERCC event which will trigger our test system.
2. Send an EnvironmentDefined with a partial environment (including eventual overrides).
3. Pick upp TERCC and EnvironmentDefined. Aggregate/merge information from recipe constraints and partial environment.
4. Send a new EnvironmentDefined with a PREVIOUS_VERSION link with a full or close-to full environment.
5. Continue sending EnvironmentDefined until environment is completed.
6. Start testing.

Any comments to this approach? :)

**Comment by e-backmark-ericsson** [comment]
Do you see any dependencies between the TERCC event and the first ED event? I mean, do you intend to link between using a CAUSE link or something?

So, there will be a chain of ED events with PREVIOUS_VERSION linking them, and each event containing the same data as the previous one plus some more? Honestly it sounds a bit strange to notify with an event that an environment is defined and later that the 'same' environment has be re-defined. It sounds more like you would need an EnvironmentModified event or something? I think that when an ED event is sent there should be some environment set up (HW or SW or combined) that could be used as is for some testing purpose.

Maybe we could set up a meeting to sort this out?

**Comment by t-persson** [comment]
Yes, a CAUSE link would connect the two.
I don't see a problem with having a partial environment before all systems have run the course of setting it up. An EnvironmentModified would work, but there's no such event at the moment which is why I thought of utilizing an EnvironmentDefined with PREVIOUS_VERSION.

We can continue the discussion on slack and post the results of our conversation here :)
