### ISSUE TITLE
Missing link to Security in header at Mission and Vision page

### ISSUE THREAD

**Issue by d-stahl-ericsson** [eiffel-community/eiffel#255]
### Description
Mission and Vision page on github.io (https://eiffel-community.github.io/mission-and-vision.html) lacks a link to security.html in the header.

### Motivation
Because the header is inconsistent between pages.

**Comment by e-backmark-ericsson** [comment]
This should not be an issue in this protocol repo, but instead in the github.io repo, right?

**Comment by d-stahl-ericsson** [comment]
You're absolutely right. No idea why this ended up here. Besides, it's fixed now. Sorry!
