### ISSUE TITLE
TERCC is misspelled in various places, including in a link type

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel#262]
### Description
The short form of EiffelTestExecutionRecipeCollectionCreatedEvent is TERCC, but in a few places TERC was used instead. Unfortunately one of those places is in the valid links section of [EiffelTestSuiteStartedEvent.md](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestSuiteStartedEvent.md), so correcting this would be a breaking change.

### Motivation
Event names should be consistently named. Technically the offending link type could have any name imaginable but I'm pretty sure the intention was for it to match the actual shortname of EiffelTestExecutionRecipeCollectionCreatedEvent.

### Exemplification
N/A

### Benefits
Consistency.

### Possible Drawbacks
Correcting this will be a backwards-incompatible change. Clients should have no technical problems adapting to the change and supporting both forms, but it's boring churn.

**Comment by e-backmark-ericsson** [comment]
I don't think that is a misspelling. TERC is short for TestExecutionRecipeCollection, and that is the noun defining what is created by a TERCC event. It's very similar to how e.g. CLM has an ARTIFACT link to ArtC. The link type is not ARTC or ARTIFACT_CREATED, but instead ARTIFACT.
So, the link type is not wrong. Are there other places where it actually is misspelled?

**Comment by magnusbaeck** [comment]
Ah, okay. That makes sense. Closing and marking as invalid.
