### ISSUE TITLE
Travis deployment of event-types-*.tar.gz broken

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel#266]
### Description
We currently have a Travis configuration that's supposed to create and add two tarballs to all releases. See the [Agen-1 release](https://github.com/eiffel-community/eiffel/releases/tag/edition-agen-1) for an example. This has been broken for a while and the [Paris release](https://github.com/eiffel-community/eiffel/releases/tag/edition-paris) didn't get any files. Here's the end of the [failing build of the Paris release](https://travis-ci.org/github/eiffel-community/eiffel/builds/759243410):

```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.5.1.tar.bz2
NaNs$ curl -sSf --retry 5 -o python-3.5.1.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
```

I'm not sure I think it's so important that the releases contain these tarballs, which leaves us with two options:
* Keep the current functionality but fix what's currently broken. It's probably wise to migrate to a GitHub Actions workflow.
* Just delete the Travis configuration and drop these tarballs.

### Motivation
If we have CI jobs for automating stuff they should work.

### Exemplification
N/A

### Benefits
Obvious.

### Possible Drawbacks
None.

**Comment by e-backmark-ericsson** [comment]
I think we should have those tarballs created. I saw that they were not when I made the last release, but I never dug into why it failed.
The benefits of having the tarballs where mentioned in this PR, and discussed further in its connected issue: https://github.com/eiffel-community/eiffel/pull/202

**Comment by e-backmark-ericsson** [comment]
Conclusion from maintainers meeting 2023-09-14:
No one has requested this feature for a long time and we don't see that it is needed. Closing this issue.
