### ISSUE TITLE
TERCC missing pattern for links.target

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel#271]
### Description
Apparently the links.target member of [TERCC](https://github.com/eiffel-community/eiffel/blob/master/schemas/EiffelTestExecutionRecipeCollectionCreatedEvent/4.0.0.json) doesn't have an associated pattern that checks that it looks like a UUID. I've verified that it's only TERCC that has this bug.

I suppose this warrants a patch bump of the event?

### Motivation
There's clearly no reason for TERCC events to be linking to non-UUIDs. This change was introduced in 2.0.0 if the event (#155) but nothing was mentioned in the commit message.

### Exemplification
N/A

### Benefits
Obvious.

### Possible Drawbacks
None.

**Comment by t-persson** [comment]
Nice catch! Yes a Patch bump seems correct since noone should link with anything but uuid
