### ISSUE TITLE
Add missing testCase.version member to TERCC event

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel#288]
### Description

The `data.batches.recipes.testCase` member in the TERCC event has duplicates of the `data.testCase` member in the TestCaseTriggered event but missing the `version` member.

### Motivation

Since we have duplicates of all other members, we should add the `version` member as well.

### Exemplification

In ETOS we use the TERCC `data.batches.recipes` for extra information about a certain test case that we run. This `version` member would help us trace the version of each testCase that was executed.

### Benefits

Both clarity in that these two events have duplicate data, but also the ability to do stuff with the `version` when publishing a TERCC.

### Possible Drawbacks

Duplicate data always hurt a little bit, but I think that should be a discussion for another time

**Comment by magnusbaeck** [comment]
We have a URI field that supposedly identifies the testcase. Shouldn't that identification also include the version, making a separate `version` field superfluous?

**Comment by e-backmark-ericsson** [comment]
Could be. But there could also be different ways of describing versions in a URI and in a more free text form, for example human readable.
