### ISSUE TITLE
Sepia links  default to lastest version instead of edition-toulouse 

### ISSUE THREAD

**Issue by jgse** [eiffel-community/eiffel#298]
### Description
the links in  https://eiffel-community.github.io/eiffel-sepia/ point to edition-toulouse  of eiffel protocol, which better to updated to latest version

### Motivation
latest protocol should be recommended to the community

**Comment by magnusbaeck** [comment]
Indeed, this should be fixed. This matter was previously reported in https://github.com/eiffel-community/eiffel-sepia/issues/1 and there's a PR that needs a little more work before we can merge it. Closing this issue.
