### ISSUE TITLE
CLM does not have a good way to point out the reason for the confidence level change.

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/eiffel#323]
### Description

Today the `CLM` does not have any link to explain the basis for the confidence level change. You could use the CONTEXT link but that only allows you to denote `ActT` or `TSS` as the basis for the confidence level change and it cannot point to a `TCT`.

A new link to describe this relationship helps make the protocol clearer.

### Motivation

Introducing a new link would describe this relation without assuming the information from the CONTEXT link.

### Exemplification

Today we would need to use a CAUSE link as see in the following [example](https://www.plantuml.com/plantuml/uml/TP2n2eCm48RtF4N0BU0BI0V3aO3Gwd1diPE83LIm7JIshrzlqDvWjpyVtzr_99zZDyNbEQfb3dqt1mtdYqvm6DzXKZia895HPF-JR1z99v_748DaUC3ynXGFdTAK6tIceIh9DQJunPIFoRGnO6jqncoSRrWvEQGMBBhMDGvgAgfI6FwFmPLY-zwvupNmTWjKN0kwYL6f-6Cb3w_x-frV).

![image](https://user-images.githubusercontent.com/54929896/196425675-5f111191-3b3b-4ccc-bb7b-e8736ef6626f.png)

### Benefits

Possibility to explicitly describe the basis for the confidence level change and allow for the `CLM` to point to a `TCT` as the reason for the confidence level change.

### Possible Drawbacks

None that I can think of

**Comment by m-linner-ericsson** [comment]
The link could be called CONFIDENCE_BASIS

**Comment by e-backmark-ericsson** [comment]
Sounds like a valid proposal. I believe this new link type should be optional, it should be fine to have multiple such links from one CLM event and their legal targets should be TCF and TSF I think.

**Comment by magnusbaeck** [comment]
What problem are we trying to address here? Using CAUSE and CONTEXT together? Or do you think CAUSE is the wrong link type altogether?

**Comment by e-backmark-ericsson** [comment]
The CAUSE link type is not good enough for to describe this relationship. CAUSE represents the causal relationship between events. If a consumer wants to know what input a certain confidence level setting had, the CAUSE link _might_ not be able to provide that. It could of course be that case that an organization decides to limit the CAUSE link target options to always be for example TCF or TSF, and thereby it will be obvious that those test activities where used as input to that decision. But the protocol allows for any event type to be used as target for a CAUSE link, so a generic consumer cannot make such assumptions. For clarity there should therefore be a dedicated link type to use for declaring the decision basis for a confidence level.
I'd say that the CONFIDENCE_BASIS link type should have TCT, and maybe also TSS, as valid targets. Or maybe TCF and TSF.

**Comment by magnusbaeck** [comment]
Comments from the [2023-01-19 protocol workshop](https://hackmd.io/fdXgYppfTYa5ObGuGd0ghw):

- The semantic difference between CAUSE and CONFIDENCE_BASIS is rather subtle and it's not clear whether and why this difference is important.
- CONFIDENCE_BASIS can link to any event type since just about anything can change the confidence in a subject.
- Let's document the CONFIDENCE_BASIS link type in a draft PR and we'll see if it flies. Can users understand when to use it and when to use CAUSE?
