### ISSUE TITLE
Add uri validation for Package URLs

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel#324]
## Description
To decrease the risk of providing invalid purls to e.g. ArtC.identity it would be good to include a more elaborated validation of the string fields representing Package URL data.

### Motivation
To improve validation of event data sent

### Exemplification
Change
```json
   "identity": {
          "type": "string",
          "pattern": "^pkg:"
        },
```
To
```json
   "identity": {
          "type": "string",
          "format": "uri",
          "pattern": "^pkg:"
        },
```

### Benefits
Better validation

### Possible Drawbacks
None

**Comment by e-backmark-ericsson** [comment]
It will probably not be enough to just restrict the format on "uri". We might need to expand the required pattern to something like the following as well:

>        "pattern": "^pkg:[^/@?#]+/[^/@?#]+[/]*[a-zA-Z0-9.@?#]+$"

or maybe even more complex than that...

The format could be easily developed using e.g. https://www.jsonschemavalidator.net/
with the following schema:
```json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
      "identity": {
        "type": "string",
        "format": "uri",
        "pattern": "^pkg:[^/@?#]+/[^/@?#]+[/]*[a-zA-Z0-9.@?#]+$"
      }
   }
}
```
and the following input (to be elaborated a lot more of course)
```json
{
    "identity": "pkg:something/namespace/name@v1.0?qualifier#subpath"
}
```

**Comment by magnusbaeck** [comment]
I can't see that `format` is a valid key in draft 04 of the JSON schema spec. It's probably not a bad idea to upgrade the spec, though. But are you suggesting that we use a stricter regexp to validate the purls? We'd have to be very careful so that we don't reject actually valid purls. Given how many possible representations of purls there are out there I'd be worried.

**Comment by e-backmark-ericsson** [comment]
Oh. Yes, format might be a more recent concept than draft 04. We should maybe lift our schema spec version as part of solving this issue then. And yes, I'm fully aware that the suggested regexp is not a regexp we should use as is. It should be seen more like an inspiration.
