### ISSUE TITLE
Rework "Introduced in" event release history column

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel#326]
### Description
The documentation of the "Introduced in" event release history column introduced in #325,

> The first edition in which this version was the latest for this event type. If the version hasn't been released in a protocol edition or if there are newer versions in the first edition where it was introduced, use "No edition set".

is hard to understand, but that's arguably because the meaning of this column is weird and doesn't match the column heading. Either the column should be renamed to something that more closely matches its intended purpose, or "No edition set" should be changed to something better, or both.

### Motivation
The current way this column is used is confusing to everyone.

### Exemplification
N/A

### Benefits
Clearer documentation, less confusion for those updating the table.

### Possible Drawbacks
None.

**Comment by e-backmark-ericsson** [comment]
I guess that would be fine
