### ISSUE TITLE
Release Arica edition of protocol

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel#333]
### Description
Once all issues for the [Arica milestone](https://github.com/eiffel-community/eiffel/milestone/7) have been closed we should release a new protocol edition, Arica.

### Motivation
There have been a sufficient number of protocol changes to warrant a new edition. Editions make it easier to reason about sets of schema versions. Some Eiffel application may choose to only update their schemas to editions and ignore non-released event versions so being too restrictive about releasing editions creates delays.

### Exemplification
N/A

### Benefits
New features can be made generally available to users of tools that only update their schemas for new editions.

### Possible Drawbacks
None.

**Comment by e-backmark-ericsson** [comment]
@magnusbaeck , not all steps in https://github.com/eiffel-community/eiffel/blob/master/releases-and-milestones/release-process.md are performed yet. I believe this issue should not be closed until it is all done.

**Comment by magnusbaeck** [comment]
Yeah, the PR shouldn't have had the "Fixes #nn" notation in the description. I'll be done with the post-release work within an hour.

**Comment by magnusbaeck** [comment]
Release process actions have been carried out, closing again.
