### ISSUE TITLE
Strict enforcement of allowed link types

### ISSUE THREAD

**Issue by fredjn** [eiffel-community/eiffel#347]
### Description
Currently the event schemas only specify the link types as having to be a string. There is no enforcement of what link types are allowed through the schema. AFAIK the protocol doesn't allow generic and arbitrary link type strings, although there is no mention of it being restricted to what is for instance documented in the vocabulary or anywhere else.

A solution to this would be adding an ENUM of allowed link types to the links object in the event schemas.

### Motivation
It becomes clearer how to use the protocol, and what is allowed and what is not.

### Exemplification
A service sends an ConfidenceLevelModifiedEvent with a link to another ConfidenceLevelModifiedEvent and the type is set to SUB_CLM, this currently validates fine using the event schema, although it uses a generic and arbitrary link type and thus IMHO _breaks_ the protocol.

Example Event 
```
{
    "data": {
        "name": "ABC123",
        "value": "SUCCESS"
    },
    "links": [
        {
            "target": "91498856-6cbb-4aee-875b-e12f2db960b9",
            "type": "SUB_CLM"
        }
    ],
    "meta": {
        "id": "92f9afcc-3b6f-4f6b-81e4-0471629103a1",
        "source": {
            "host": "host.name",
            "name": "My Eiffel Skicking Service"
        },
        "time": 4,
        "type": "EiffelConfidenceLevelModifiedEvent",
        "version": "3.2.0"
    }
}
```

### Benefits
Makes it harder to create and send improper and/or broken events.

### Possible Drawbacks
Any existing implementations that use validation and have events that use generic and arbitrary link types will break.

**Comment by fredjn** [comment]
As it happens this had already been reported and denied(?) - Ref. https://github.com/eiffel-community/eiffel/issues/148

**Comment by e-backmark-ericsson** [comment]
> As it happens this had already been reported and denied(?) - Ref. #148

Was this denied? I fail to see that it was. To me, I'd still like to see link type validation as being part of the schema. It was not possible in the schema version we used from the beginning, but nowadays I believe it should be possible.

**Comment by fredjn** [comment]
Well according to Daniels comments I got the feeling that we wanted to keep the protocol less strict and more open. Thus, as Daniel said, adding link validation would not be favorable. However this was some time ago and opinions do sometime sway/change.

**Comment by fredjn** [comment]
Duplicate of #148, closing (...again)
