### ISSUE TITLE
ActF/TCF/TSF should include digest of persistent log contents

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel#358]
### Description
Just like ArtC can include the digest of the artifact files to enable detection of tampering (via `data.fileInformation.integrityProtection`), it should also be possible to include the digest of the persistent logs announced in ActF, TCF, and TSF (e.g. `data.persistentLogs.integrityProtection`).

If implemented, we should probably define a new struct type (like [EiffelMetaProperty](https://github.com/eiffel-community/eiffel/tree/master/definitions/EiffelMetaProperty) and [EiffelEventLink](https://github.com/eiffel-community/eiffel/tree/master/definitions/EiffelEventLink)) for the integrityProtection members to reduce duplication and enable nicer SDKs. 

### Motivation
Activity logs could contain audit information or similar where it's vital that tampering (or corruption) is detected. Right now the only way of using Eiffel to convey that information is to expose the logs as artifacts, and while that's not completely unreasonable, we already provide a standard mechanism for exposing activity logs and it would be a pity to not support this use case.

### Exemplification
N/A

### Benefits
Allow detection of tampering or corruption of activity logs (if that information is provided by the publisher).

### Possible Drawbacks
None.

**Comment by m-linner-ericsson** [comment]
Sounds like an reasonable idea. We do have the same type of logs in [TCF](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestCaseFinishedEvent.md#datapersistentlogs)  and [TSF](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestSuiteFinishedEvent.md#datapersistentlogs), should we add it for those events also?

**Comment by magnusbaeck** [comment]
Ah, right. Forgot about those. Yes, definitely. And that makes the case for a new struct type even stronger.
